#项目配置
################################服务器################################
#后台地址
#mall_url=https://127.0.0.1:8081/dashop/
#图片地址
#mall_upload_url=https://127.0.0.1:8081/mallupload/
#图片存放路径地址
#mall_upload_path= /home/apps/web/dashop/


################################本地################################
#后台地址
mall_url=http\://127.0.0.1:8082/dashop/
#图片地址
mall_upload_url=http\://127.0.0.1:8082
#图片存放路径地址
mall_upload_path = D:\\deploy\\tomcat-8.0.35_8082\\webapps\\mallupload

################################E:\da_run\tomcat-8.0.35_8086


