#微信支付配置
#################################
#微信小程序，微信认证的自己应用ID
wx.appid=wx9b2c7cd55e9cb5ab
wx.appsecret=1bf55e6d5d46453d0f600e5888a1d7a4
#商户id
wx.mchid=1511495101
#API密钥
wx.api.secret=GHcluEUIdiZLLaAasGz3yoG6XR6lsihY
#################################

#APP微信支付，支付认证的自己应用ID
wx.appid_app=wx5160f8411c9f33ea
#商户id
wx.mchid_app=1512208141
#API密钥
wx.api.secret_app=OI5dbmL3Ez6AKPm8y4twOi5fQv1sVBtn

#微信公众号
wx.appid_gzh=wx08828d48d008edd7
wx.appsecret_gzh=03b64310506e9cbd14865c5fc8cc3deb